config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  resources :time_cards
  resources :user_infos
  resources :time_types
  resources :month_infos

  post 'time_cards/populate/:day' => 'time_cards#populate' , as: 'populate_time_card'

  root 'welcome#index'

end

app/controllers/time_types_controller.rb
class TimeTypesController < ApplicationController
  before_action :set_time_type, only: [:show, :edit, :update, :destroy]

  # GET /time_types
  # GET /time_types.json
  def index
    @time_types = TimeType.all
  end

  # GET /time_types/1
  # GET /time_types/1.json
  def show
  end

  # GET /time_types/new
  def new
    @time_type = TimeType.new
  end

  # GET /time_types/1/edit
  def edit
  end

  # POST /time_types
  # POST /time_types.json
  def create
    @time_type = TimeType.new(time_type_params)

    respond_to do |format|
      if @time_type.save
        format.html { redirect_to @time_type, notice: 'Time type was successfully created.' }
        format.json { render :show, status: :created, location: @time_type }
      else
        format.html { render :new }
        format.json { render json: @time_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_types/1
  # PATCH/PUT /time_types/1.json
  def update
    respond_to do |format|
      if @time_type.update(time_type_params)
        format.html { redirect_to @time_type, notice: 'Time type was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_type }
      else
        format.html { render :edit }
        format.json { render json: @time_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_types/1
  # DELETE /time_types/1.json
  def destroy
    @time_type.destroy
    respond_to do |format|
      format.html { redirect_to time_types_url, notice: 'Time type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_type
      @time_type = TimeType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_type_params
      params.require(:time_type).permit(:name, :short_name, :color)
    end
end

app/helpers/time_types_helper.rb
module TimeTypesHelper
end

app/views/time_types/_form.html.erb
<%= form_for(@time_type, html: {class: 'form-horizontal'}) do |f| %>
    <% if @time_type.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@time_type.errors.count, "error") %> prohibited this time_type from being saved:</h2>

          <ul>
            <% @time_type.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field form-group">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>

    <div class="field form-group">
      <%= f.label :short_name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-4">
        <%= f.text_field :short_name, class: 'form-control', maxlength: 2 %>
      </div>
    </div>

    <div class="field form-group">
      <%= f.label :color, class: 'col-sm-2 control-label' %>
      <div class="col-sm-4">
        <% if @time_type.new_record? %>
           <%= f.color_field :color, {value: '#ffffff'}%>
        <% else %>
            <%= f.color_field :color %>
        <% end %>
      </div>
    </div>

    <div class="actions form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-success' %>
      </div>
    </div>
<% end %>

app/views/time_types/edit.html.erb
<h1>Editing Time Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @time_type, class: 'btn btn-default' %>
<%= link_to 'Back', time_types_path,  class: 'btn btn-default' %>

app/views/time_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Time Types</h1>


<div class="row">
  <div class="col-xs-12" style="text-align: right;" >
    <%= link_to 'New Time type', new_time_type_path, class: 'btn btn-success' %>
  </div>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Short name</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @time_types.each_with_index do |time_type, index| %>
      <tr>
        <td><%=index+1 %></td>
        <td><%= time_type.name %></td>
        <td><%= time_type.short_name %></td>
        <td><%= color_field_tag time_type.color, time_type.color, disabled: true%> </td>
        <td><%= link_to 'Show', time_type %></td>
        <td><%= link_to 'Edit', edit_time_type_path(time_type) %></td>
        <td><%= link_to 'Destroy', time_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/time_types/new.html.erb
<h1>New Time Type</h1>

<%= render 'form' %>

<%= link_to 'Back', time_types_path, class: 'btn btn-default' %>

app/views/time_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @time_type.name %>
</p>

<p>
  <strong>Short name:</strong>
  <%= @time_type.short_name %>
</p>

<p>
  <strong>Color:</strong>
  <%= color_field_tag @time_type.color, @time_type.color, disabled: true%>
</p>

<%= link_to 'Edit', edit_time_type_path(@time_type), class: 'btn btn-default' %>
<%= link_to 'Back', time_types_path, class: 'btn btn-default' %>