config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  resources :time_cards
  resources :user_infos
  resources :time_types
  resources :month_infos

  post 'time_cards/populate/:day' => 'time_cards#populate' , as: 'populate_time_card'

  root 'welcome#index'

end

app/models/month_info.rb
class MonthInfo < ActiveRecord::Base
  validates :month, :quota, :presence => true
  validates_numericality_of :quota, greater_than: 100

end

app/controllers/month_infos_controller.rb
class MonthInfosController < ApplicationController
  before_action :set_month_info, only: [:show, :edit, :update, :destroy]

  # GET /month_infos
  # GET /month_infos.json
  def index
    @month_infos = MonthInfo.all
  end

  # GET /month_infos/1
  # GET /month_infos/1.json
  def show
  end

  # GET /month_infos/new
  def new
    @month_info = MonthInfo.new
  end

  # GET /month_infos/1/edit
  def edit
  end

  # POST /month_infos
  # POST /month_infos.json
  def create
    @month_info = MonthInfo.new(month_info_params)

    respond_to do |format|
      if @month_info.save
        format.html { redirect_to @month_info, notice: 'Month info was successfully created.' }
        # format.json { render :show, status: :created, location: @month_info }
      else
        format.html { render :new }
        # format.json { render json: @month_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /month_infos/1
  # PATCH/PUT /month_infos/1.json
  def update
    respond_to do |format|
      if @month_info.update(month_info_params)
        format.html { redirect_to @month_info, notice: 'Month info was successfully updated.' }
        # format.json { render :show, status: :ok, location: @month_info }
      else
        format.html { render :edit }
        # format.json { render json: @month_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /month_infos/1
  # DELETE /month_infos/1.json
  def destroy
    @month_info.destroy
    respond_to do |format|
      format.html { redirect_to month_infos_url, notice: 'Month info was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_month_info
      @month_info = MonthInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def month_info_params
      params.require(:month_info).permit(:month, :editable, :quota)
    end
end

app/helpers/month_infos_helper.rb
module MonthInfosHelper
end

app/views/month_infos/_form.html.erb
<%= form_for(@month_info, html: {class: 'form-horizontal'}) do |f| %>
    <% if @month_info.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@month_info.errors.count, "error") %> prohibited this month_info from being saved:</h2>

          <ul>
            <% @month_info.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field form-group">
      <%= f.label :month, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.date_select :month, discard_day: true, class: 'form-control' %>
        <input type="text" data-provide='datepicker' >


      </div>




    </div>

    <div class="field form-group">
      <%= f.label :editable, class: 'col-sm-2 control-label' %>
      <div class="col-sm-1" >
        <%= f.check_box :editable, class: 'form-control', style:'height: 20px;'%>
      </div>
    </div>

    <div class="field form-group">
      <%= f.label :quota, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.number_field :quota, class: 'form-control' %>
      </div>
    </div>

    <div class="actions form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-success' %>
      </div>
    </div>

<% end %>

app/views/month_infos/edit.html.erb
<h1>Editing Month Info</h1>


<%= render 'form' %>

<%= link_to 'Show', @month_info, class: "btn btn-default" %>
<%= link_to 'Back', month_infos_path, class: "btn btn-default" %>

app/views/month_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Month Infos</h1>

<div class="row">
  <div class="col-xs-12" style="text-align: right;" >
    <%= link_to 'New Month info', new_month_info_path, class: 'btn btn-success' %>
  </div>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Month</th>
      <th>Editable</th>
      <th>Quota</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @month_infos.each_with_index  do |month_info, index| %>
      <tr>
        <td><%=index+1 %></td>
        <td><%= month_info.month.to_formatted_s(:month_and_year) %></td>
        <td style='padding-left: 20px;'>  <% if month_info.editable %>
              <span class="glyphicon glyphicon-check"></span>
          <% else %>
              <span class="glyphicon glyphicon-unchecked"></span>
          <% end %>
        </td>
        <td><%= month_info.quota %></td>
        <td><%= link_to 'Show', month_info %></td>
        <td><%= link_to 'Edit', edit_month_info_path(month_info) %></td>
        <td><%= link_to 'Destroy', month_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/month_infos/new.html.erb
<h1>New Month Info</h1>

<%= render 'form' %>

<%= link_to 'Back', month_infos_path, class: "btn btn-default" %>

app/views/month_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Month:</strong>
  <%= @month_info.month.to_formatted_s(:month_and_year)  %>
</p>

<p>
  <strong>Editable:</strong>
  <% if @month_info.editable %>
      <span class="glyphicon glyphicon-check"></span>
  <% else %>
      <span class="glyphicon glyphicon-unchecked"></span>
  <% end %>

</p>

<p>
  <strong>Quota:</strong>
  <%= @month_info.quota %>
</p>

<%= link_to 'Edit', edit_month_info_path(@month_info), class: "btn btn-default" %>
<%= link_to 'Back', month_infos_path, class: "btn btn-default" %>