config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  resources :time_cards
  resources :user_infos
  resources :time_types
  resources :month_infos

  post 'time_cards/populate/:day' => 'time_cards#populate' , as: 'populate_time_card'

  root 'welcome#index'

end

app/models/user_info.rb
class UserInfo < ActiveRecord::Base
end

app/controllers/user_infos_controller.rb
class UserInfosController < ApplicationController
  before_action :set_user_info, only: [:show, :edit, :update, :destroy]

  # GET /user_infos
  # GET /user_infos.json
  def index
    @user_infos = UserInfo.all
  end

  # GET /user_infos/1
  # GET /user_infos/1.json
  def show
  end

  # GET /user_infos/new
  def new
    @user_info = UserInfo.new
  end

  # GET /user_infos/1/edit
  def edit
  end

  # POST /user_infos
  # POST /user_infos.json
  def create
    @user_info = UserInfo.new(user_info_params)

    respond_to do |format|
      if @user_info.save
        format.html { redirect_to @user_info, notice: 'User info was successfully created.' }
        format.json { render :show, status: :created, location: @user_info }
      else
        format.html { render :new }
        format.json { render json: @user_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_infos/1
  # PATCH/PUT /user_infos/1.json
  def update
    respond_to do |format|
      if @user_info.update(user_info_params)
        format.html { redirect_to @user_info, notice: 'User info was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_info }
      else
        format.html { render :edit }
        format.json { render json: @user_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_infos/1
  # DELETE /user_infos/1.json
  def destroy
    @user_info.destroy
    respond_to do |format|
      format.html { redirect_to user_infos_url, notice: 'User info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_info
      @user_info = UserInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_info_params
      params.require(:user_info).permit(:email, :quota, :active)
    end
end

app/helpers/user_infos_helper.rb
module UserInfosHelper
end

app/views/user_infos/_form.html.erb
<%= form_for(@user_info, html: {class: 'form-horizontal'}) do |f| %>
    <% if @user_info.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user_info.errors.count, "error") %> prohibited this user_info from being saved:</h2>

          <ul>
            <% @user_info.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field form-group">
      <%= f.label :email, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.email_field :email, class: 'form-control' %>
      </div>
    </div>
    <div class="field  form-group">
      <%= f.label :quota, class: 'col-sm-2 control-label' %><br>

      <div class="col-sm-4">
        <%= f.number_field :quota, class: 'form-control' %>
      </div>
    </div>
    <div class="field">
      <%= f.label :user_active, class: 'col-sm-2 control-label' %><br>
      <div class="col-sm-1">
        <%= f.check_box :user_active, class: 'form-control', style:'height: 20px;' %>
      </div>
    </div>
    <div class="actions form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-success' %>
      </div>
    </div>
<% end %>

app/views/user_infos/edit.html.erb
<h1>Editing User Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_info, class: 'btn btn-default' %>
<%= link_to 'Back', user_infos_path, class: 'btn btn-default' %>

app/views/user_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Infos</h1>


<div class="row">
  <div class="col-xs-12" style="text-align: right;" >
    <%= link_to 'New User Info', new_user_info_path, class: 'btn btn-success' %>
  </div>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Email</th>
      <th>Quota</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_infos.each_with_index do |user_info, index| %>
      <tr>
        <td><%=index+1 %></td>
        <td><%= user_info.email %></td>
        <td><%= user_info.quota %></td>
        <td style='padding-left: 20px;'>
          <% if user_info.user_active %>
              <span class="glyphicon glyphicon-check"></span>
          <% else %>
              <span class="glyphicon glyphicon-unchecked"></span>
          <% end %>
        <td><%= link_to 'Show', user_info %></td>
        <td><%= link_to 'Edit', edit_user_info_path(user_info) %></td>
        <td><%= link_to 'Destroy', user_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/user_infos/new.html.erb
<h1>New User Info</h1>

<%= render 'form' %>

<%= link_to 'Back', user_infos_path, class: 'btn btn-default'%>

app/views/user_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user_info.email %>
</p>

<p>
  <strong>Quota:</strong>
  <%= @user_info.quota %>
</p>

<p>
  <strong>Active:</strong>
  <% if @user_info.user_active %>
      <span class="glyphicon glyphicon-ok"></span>
  <% else %>
      <span class="glyphicon glyphicon-unchecked"></span>
  <% end %>
</p>

<%= link_to 'Edit', edit_user_info_path(@user_info), class: 'btn btn-default' %>
<%= link_to 'Back', user_infos_path, class: 'btn btn-default' %>