config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  resources :time_cards
  resources :user_infos
  resources :time_types
  resources :month_infos

  post 'time_cards/populate/:day' => 'time_cards#populate' , as: 'populate_time_card'

  root 'welcome#index'

end

app/models/time_card.rb
class TimeCard < ActiveRecord::Base
  belongs_to :time_type

  validates :day, :hours_worked, :quota_day, :presence => true
  validates_numericality_of  :hours_worked, :quota_day, :leaving_time, :overtime


  before_update do |time_card|
    #reset if time type was set
    if time_card.time_type.present?
      time_card.hours_worked = 0
      time_card.leaving_time = 0
      time_card.overtime = 0
    end
  end

end

app/controllers/time_cards_controller.rb
class TimeCardsController < ApplicationController

  before_action :set_time_card, only: [:show, :edit, :update, :destroy]

  # GET /time_cards
  # GET /time_cards.json
  def index

    @current_date = params[:selected_date]
    if !@current_date
      @current_date = Date.today
    else
      @current_date = Date.parse(@current_date)
    end

    @time_cards = TimeCard.where(day: @current_date.beginning_of_month..@current_date.end_of_month)
  end

  # GET /time_cards/1
  # GET /time_cards/1.json
  def show
    # @current_date = params[:id]
    # render index
  end


  # GET /time_cards/new
  def new
    _selected_day = params[:selected_day]
    @time_card = TimeCard.new(day: _selected_day)
  end

  # GET /time_cards/1/edit
  def edit
  end

  # POST /time_cards
  # POST /time_cards.json
  def create
    @time_card = TimeCard.new(time_card_params)

    respond_to do |format|
      if @time_card.save
        # format.html { redirect_to @time_card, notice: 'Time card was successfully created.' }
        # format.json { render :show, status: :created, location: @time_card }
        format.html { redirect_to time_cards_path, notice: 'Time card was successfully created.' }
        format.json { render :index, status: :created, location: time_cards_path }
      else
        format.html { render :new }
        format.json { render json: @time_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_cards/1D
  # PATCH/PUT /time_cards/1.json
  def update

    respond_to do |format|
      if @time_card.update(time_card_params)
        # format.html { redirect_to @time_card, notice: 'Time card was successfully updated.' }
        # format.json { render :show, status: :ok, location: @time_card }
        format.html { redirect_to time_cards_path, notice: 'Time card was successfully updated.' }
        format.json { render :index, status: :ok, location: time_cards_path }
      else
        format.html { render :edit }
        format.json { render json: @time_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_cards/1
  # DELETE /time_cards/1.json
  def destroy
    @time_card.destroy
    respond_to do |format|
      format.html { redirect_to time_cards_url, notice: 'Time card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def populate
    _day = params[:day]
    #TODO set the quota instead of 8 hours
    @time_card = TimeCard.new(day: _day, hours_worked: 8, quota_day: 8, on_call:false, working_home:false)
    respond_to do |format|
      if @time_card.save
        format.html { redirect_to time_cards_path, notice: 'Time card was for ' + _day.to_s+ ' successfully created.' }
        format.json { render :index, status: :created, location: time_cards_path }
      else
        format.html { render :time_cards_path }
        format.json { render json: @time_card.errors, status: :unprocessable_entity }
      end
    end

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_time_card
    @time_card = TimeCard.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def time_card_params
    params.require(:time_card).permit(:day, :time_type_id, :on_call, :working_home, :comment, :hours_worked, :leaving_time, :overtime, :quota_day)
  end
end

app/helpers/time_cards_helper.rb
module TimeCardsHelper


  # Time card has a time type?
  # @param [Object] time_card
  # @return Boolean
  def time_type_exist?(time_card)
    time_card.time_type.present?
  end

  def time_card_with_day(time_cards, day)
    time_cards.select{ |elem| elem.day == day}.first
  end
end

app/views/time_cards/_day_cell.html.erb
<div class="panel panel-default" style="margin: 0">
  <div class="panel-heading">
    <h3 class="panel-title day-title">
      <%= if time_card_day
            link_to day.day, edit_time_card_path(time_card_day)
          else
            link_to day.day, new_time_card_path(:selected_day => day)
          end
      %>
    </h3>
  </div>
  <%
     if !time_card_day.nil? && !time_card_day.time_type_id.nil?
       _color_panel_background = time_card_day.time_type.color
     else
       _color_panel_class = 'working-from-home' if !time_card_day.nil? && time_card_day.working_home
       _color_panel_class = 'on-call' if !time_card_day.nil? && time_card_day.on_call
     end
  %>

  <div class="panel-body <%= _color_panel_class %>" style="background-color: <%= _color_panel_background %>">
    <%= if time_card_day.nil?
          link_to populate_time_card_path(:day => day), :method => :post do %>
            <button class="btn btn-flat btn-default btn-cell" type="button">
              <span class="badge-hour">FILL</span>
            </button>
        <% end
           else
             link_to edit_time_card_path(time_card_day) do %>
            <button class="btn btn-primary btn-cell" type="button">

              <% # display the time type short name
                 if time_type_exist?(time_card_day) %>
                  <span class="badge-hour"><%= time_card_day.time_type.short_name %></span>
              <% else
                   # display the hours and extra time
                   if time_card_day.hours_worked > time_card_day.quota_day %>
                      <span class="glyphicon glyphicon-plus-sign"></span>
                  <% elsif time_card_day.hours_worked < time_card_day.quota_day %>
                      <span class="glyphicon glyphicon-minus-sign"></span>
                  <% end %>
                  <span class="badge-hour"><%= time_card_day ? time_card_day.hours_worked : '' %></span>
                  <span class="badge"><%= time_card_day ? time_card_day.quota_day : '' %></span>
              <% end %>
            </button>
        <% end # end do
           end # if timecard.nil?  %>

    <p style="margin-bottom:10px; "></p>

    <div class="row">
      <div class="col-xs-6">
        <span class="badge"><%= time_card_day.leaving_time unless time_card_day.nil? %></span>
        <label><%= '' if time_card_day.nil? %></label>
      </div>
      <div class="col-xs-6">
        <span class="badge"><%= time_card_day.overtime unless time_card_day.nil? %></span>
        <label><%= '' if time_card_day.nil? %></label>
      </div>
    </div>


  </div>
</div>

app/views/time_cards/_form.html.erb
<%= form_for(@time_card, html: {class: 'form-horizontal'}) do |f| %>
    <% if @time_card.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@time_card.errors.count, 'error') %> prohibited this time_card from being saved:</h2>

          <ul>
            <% @time_card.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :day, class: 'col-lg-2 control-label' %>
      <div class="col-lg-8">
        <span class="label label-default"><%= @time_card.day %></span>
        <!--f.date_select :day -->
      </div>
    </div>
    <div class="form-group">
      <%= f.label :time_type_id, class: 'col-lg-2 control-label' %>
      <div class="col-lg-8">
        <%= f.select(:time_type_id, TimeType.all.collect {|p| [ p.name, p.id ] }, include_blank: 'None', class: 'dropdown') %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :on_call, class: 'col-lg-2 control-label' %>
      <div class="col-lg-4">
        <%= f.check_box :on_call %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :working_home, class: 'col-lg-2 control-label' %>
      <div class="col-lg-4">
        <%= f.check_box :working_home %>
      </div>
    </div>


    <div class="form-group">
      <%= f.label :hours_worked, class: 'col-lg-2 control-label' %><br>

      <div class="col-lg-4">
        <%= f.number_field :hours_worked, class: "form-control" %>
      </div>
    </div>


    <div class="form-group">
      <%= f.label :quota_day, class: 'col-lg-2 control-label' %>
      <div class="col-lg-4">
        <%= f.number_field :quota_day, class: "form-control", disabled: '' %>
      </div>
    </div>

    <div><hr></div>

    <div class="form-group">
      <%= f.label :leaving_time, class: 'col-lg-2 control-label' %>
      <div class="col-lg-4">
        <%= f.number_field :leaving_time, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :overtime, class: 'col-lg-2 control-label' %>
      <div class="col-lg-4">
        <%= f.number_field :overtime, class: "form-control"%>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :comment, class: 'col-lg-2 control-label' %>
      <div class="col-lg-8">
        <%= f.text_area :comment, class: "form-control", rows: 2 %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= f.submit class: 'btn btn-primary'%>
        <span></span>
        <%= link_to 'Destroy', @time_card, method: :delete, data: {confirm: 'Are you sure?'} ,
                    class: 'btn btn-default', style:'float: right'%>
      </div>
    </div>

<% end %>

app/views/time_cards/edit.html.erb
<%= link_to 'Back', time_cards_path, class: 'btn btn-link' %>

<h1>Editing Time Card</h1>

<%= render 'form' %>

app/views/time_cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Time Cards</h1>

<div class="row" style="padding-bottom: 20px">
  <div class="col-xs-3 col-xs-offset-1">
        <%= label_tag('datetimepicker10', 'Selected Month') %>
    </div>
  <div class="col-xs-5">

        <div class='input-group date' id='datetimepicker10'>
          <input type='text' class="form-control"/>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar">
                </span>
            </span>
        </div>
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker10').datetimepicker({
                    viewMode: 'years',
                    format: 'MM/YYYY',
                    defaultDate: '<%=@current_date%>'
                });
            });
        </script>
  </div>
</div>

<div class="row time-card-calendar">
  <div class="col-xs-10">
    <%= calendar(:year => @current_date.year, :month => @current_date.month, :first_day_of_week => 1, :show_today => true,
                 :month_header => false, :show_other_months => false) do |d|
      [render(partial: 'day_cell', locals: {time_card_day: time_card_with_day(@time_cards,d), day:d}), {class: 'time-card-cell'}]
    end
    %>
  </div>
</div>
<br>
<br>











<!--<div class="row">-->
  <!--<div class="col-xs-12" style="text-align: right;">-->
    <!--<!%= link_to 'New Time card', new_time_card_path, class: 'btn btn-success' %>-->
  <!--</div>-->
<!--</div>-->

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Day</th>
    <th>On call</th>
    <th>Working home</th>
    <th>Comment</th>
    <th>Hours worked</th>
    <th>Quota day</th>
    <th>Leaving time</th>
    <th>Overtime</th>
    <th>Time type</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @time_cards.each do |time_card| %>
      <tr>
        <td><%= time_card.day %></td>
        <td><%= time_card.on_call %></td>
        <td><%= time_card.working_home %></td>
        <td><%= time_card.comment %></td>
        <td><%= time_card.hours_worked %></td>
        <td><%= time_card.quota_day %></td>
        <td><%= time_card.leaving_time %></td>
        <td><%= time_card.overtime %></td>
        <td><%= time_card.time_type_id %></td>
        <td><%= link_to 'Show', time_card %></td>
        <td><%= link_to 'Edit', edit_time_card_path(time_card) %></td>
        <td><%= link_to 'Destroy', time_card, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/time_cards/new.html.erb
<h1>New Time Card</h1>

<%= render 'form' %>

<%= link_to 'Back', time_cards_path %>

app/views/time_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @time_card.day %>
</p>

<p>
  <strong>On call:</strong>
  <%= @time_card.on_call %>
</p>

<p>
  <strong>Working home:</strong>
  <%= @time_card.working_home %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @time_card.comment %>
</p>

<p>
  <strong>Hours worked:</strong>
  <%= @time_card.hours_worked %>
</p>

<p>
  <strong>Quota day:</strong>
  <%= @time_card.quota_day %>
</p>

<%= link_to 'Edit', edit_time_card_path(@time_card) %> |
<%= link_to 'Back', time_cards_path %>